In [1]:
# Dependencies.
# Data.
import pandas as pd
import numpy as np

# Helper functions.
from feature_processor import lemmatizeAssist, processText, columnMerger

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\emteb\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\emteb\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\emteb\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\emteb\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\emteb\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [2]:
# Load dataset.
df = pd.read_csv("resources/movie_dataset.csv")

# Select rows needed.
df = df[['title', 'rating', 'genre', 'director', 'cast1', 'cast2', 'cast3', 'cast4', 'overview']]

# Display.
display(df.info())
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3385 entries, 0 to 3384
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     3385 non-null   object
 1   rating    3385 non-null   float64
 2   genre     3385 non-null   object
 3   director  3385 non-null   object
 4   cast1     3385 non-null   object
 5   cast2     3381 non-null   object
 6   cast3     3375 non-null   object
 7   cast4     3374 non-null   object
 8   overview  3385 non-null   object
dtypes: float64(1), object(8)
memory usage: 238.1+ KB

None

,title,rating,genre,director,cast1,cast2,cast3,cast4,overview
0,The Shawshank Redemption,9.3,Drama,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,Two imprisoned men bond over a number of years...
1,The Godfather,9.2,"Crime, Drama",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,An organized crime dynasty's aging patriarch t...
2,The Dark Knight,9.0,"Action, Crime, Drama",Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,When the menace known as the Joker wreaks havo...
3,The Godfather: Part II,9.0,"Crime, Drama",Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,The early life and career of Vito Corleone in ...
4,12 Angry Men,9.0,"Crime, Drama",Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,A jury holdout attempts to prevent a miscarria...

In [3]:
# Drop duplicate titles.
c_df = df.drop_duplicates('title')

c_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3067 entries, 0 to 3384
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     3067 non-null   object
 1   rating    3067 non-null   float64
 2   genre     3067 non-null   object
 3   director  3067 non-null   object
 4   cast1     3067 non-null   object
 5   cast2     3063 non-null   object
 6   cast3     3057 non-null   object
 7   cast4     3056 non-null   object
 8   overview  3067 non-null   object
dtypes: float64(1), object(8)
memory usage: 239.6+ KB

In [4]:
# Change Sci-Fi to Science Fiction in genre.
c_df['genre'] = c_df.genre.apply(lambda x: x.replace("Sci-Fi", "Science Fiction"))

c_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3067 entries, 0 to 3384
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     3067 non-null   object
 1   rating    3067 non-null   float64
 2   genre     3067 non-null   object
 3   director  3067 non-null   object
 4   cast1     3067 non-null   object
 5   cast2     3063 non-null   object
 6   cast3     3057 non-null   object
 7   cast4     3056 non-null   object
 8   overview  3067 non-null   object
dtypes: float64(1), object(8)
memory usage: 239.6+ KB

C:\Users\emteb\AppData\Local\Temp\ipykernel_10444\3774683284.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_df['genre'] = c_df.genre.apply(lambda x: x.replace("Sci-Fi", "Science Fiction"))

In [5]:
# Smush the overview.
c_df['lemma_text'] = c_df.overview.apply(lambda x: processText(x))

display(c_df.head())

C:\Users\emteb\AppData\Local\Temp\ipykernel_10444\1342342164.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_df['lemma_text'] = c_df.overview.apply(lambda x: processText(x))

,title,rating,genre,director,cast1,cast2,cast3,cast4,overview,lemma_text
0,The Shawshank Redemption,9.3,Drama,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,Two imprisoned men bond over a number of years...,two imprisoned men bond number year find solac...
1,The Godfather,9.2,"Crime, Drama",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,An organized crime dynasty's aging patriarch t...,organize crime dynasty age patriarch transfer ...
2,The Dark Knight,9.0,"Action, Crime, Drama",Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,When the menace known as the Joker wreaks havo...,menace know joker wreak havoc chaos people got...
3,The Godfather: Part II,9.0,"Crime, Drama",Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,The early life and career of Vito Corleone in ...,early life career vito corleone 1920s new york...
4,12 Angry Men,9.0,"Crime, Drama",Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,A jury holdout attempts to prevent a miscarria...,jury holdout attempt prevent miscarriage justi...

In [6]:
# Smush all columns together.
c_df['feature'] = c_df.apply(lambda row: columnMerger(row), axis = 1)

c_df.head()

C:\Users\emteb\AppData\Local\Temp\ipykernel_10444\3904464007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_df['feature'] = c_df.apply(lambda row: columnMerger(row), axis = 1)

,title,rating,genre,director,cast1,cast2,cast3,cast4,overview,lemma_text,feature
0,The Shawshank Redemption,9.3,Drama,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,Two imprisoned men bond over a number of years...,two imprisoned men bond number year find solac...,two imprisoned men bond number year find solac...
1,The Godfather,9.2,"Crime, Drama",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,An organized crime dynasty's aging patriarch t...,organize crime dynasty age patriarch transfer ...,organize crime dynasty age patriarch transfer ...
2,The Dark Knight,9.0,"Action, Crime, Drama",Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,When the menace known as the Joker wreaks havo...,menace know joker wreak havoc chaos people got...,menace know joker wreak havoc chaos people got...
3,The Godfather: Part II,9.0,"Crime, Drama",Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,The early life and career of Vito Corleone in ...,early life career vito corleone 1920s new york...,early life career vito corleone 1920s new york...
4,12 Angry Men,9.0,"Crime, Drama",Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,A jury holdout attempts to prevent a miscarria...,jury holdout attempt prevent miscarriage justi...,jury holdout attempt prevent miscarriage justi...

In [7]:
# Grab columns.
c_df = c_df[['title', 'rating', 'feature']]

c_df.head()

,title,rating,feature
0,The Shawshank Redemption,9.3,two imprisoned men bond number year find solac...
1,The Godfather,9.2,organize crime dynasty age patriarch transfer ...
2,The Dark Knight,9.0,menace know joker wreak havoc chaos people got...
3,The Godfather: Part II,9.0,early life career vito corleone 1920s new york...
4,12 Angry Men,9.0,jury holdout attempt prevent miscarriage justi...

In [8]:
# It's done.
c_df.to_csv("resources/ml_movie.csv", index = False)